meta:
  engine: 4.1.0
  version: 0.1
  author: jjongpark@gmail.com

units:
  # Width of a MX key cap
  k: $default_width
  # Gap between adjacent key caps
  pad: 1

points:
  # Rotate in order to model columns as rowsModel 
  rotate: -90
  zones:
    # Left-side keyboard.
    # Keys are added from the top row to the bottom row, 
    # and from left to right in the same row.
    left:
      # Adjust for KiCAD
      anchor:
        shift: [3u, 2u]

      # This key-level rotation is to counter the zone-level
      # rotation above so that swiches are oriented upward
      key:
        adjust:
          rotate: 90
      columns:
        function:
          key:
            rownet_left: LR1
          rows:
            esc:
              padding: 2u
              colnet_left: LC1
            f1:
              colnet_left: LC3
            f2:
              colnet_left: LC4
            f3:
              colnet_left: LC5
            f4:
              colnet_left: LC6
            f5:
              colnet_left: LC7
        num:
          key:
            # add some space between function keys and the number keys
            spread: 1.3u
            rownet_left: LR2
          rows:
            tilda:
              colnet_left: LC1
            one:
              colnet_left: LC2
            two:
              colnet_left: LC3
            three:
              colnet_left: LC4
            four:
              colnet_left: LC5
            five:
              colnet_left: LC6
            six:
              colnet_left: LC7
        top:
          key:
            rownet_left: LR3
          rows:
            tab:
              width: 1.5k
              padding: (1.5k+pad+1u)/2
              shift: [0, (1.5k+pad-1u)/2]
              bind: [(1.5k+pad-1u)/2, 0]
              colnet_left: LC1
            q:
              colnet_left: LC2
            w:
              colnet_left: LC3
            e:
              colnet_left: LC4
            r:
              colnet_left: LC5
            t:
              colnet_left: LC6
        mid:
          key:
            rownet_left: LR4
          rows:
            caps:
              width: 1.75k
              padding: (1.75k+pad+1u)/2
              shift: [0, (1.75k+pad-1u)/2]
              bind: [(1.75k+pad-1u)/2, 0]
              colnet_left: LC1
            a:
              colnet_left: LC2
            s:
              colnet_left: LC3
            d:
              colnet_left: LC4
            f:
              colnet_left: LC5
            g:
              colnet_left: LC6
        bottom:
          key:
            rownet_left: LR5
          rows:
            shift:
              width: 2.25k
              padding: (2.25k+pad+1u)/2
              shift: [0, (2.25k+pad-1u)/2]
              bind: [(2.25k+pad-1u)/2, 0]
              colnet_left: LC1
            z:
              colnet_left: LC2
            x:
              colnet_left: LC3
            c:
              colnet_left: LC4
            v:
              colnet_left: LC5
            b:
              colnet_left: LC6
        meta:
          key:
            rownet_left: LR6
          rows:
            ctrl:
              width: 1.25k
              padding: (1.25k+pad + 1.25k+pad)/2
              shift: [0, (1.25k+pad - 1u)/2]
              bind: [(1.25k+pad - 1u)/2, 0]
              colnet_left: LC1
            win:
              width: 1.25k
              padding: (1.25k+pad + 1.25k+pad)/2
              bind: [(1.25k+pad - 1.25k)/2, 0]
              colnet_left: LC2
            alt:
              width: 1.25k
              padding: (1.25k+pad + 3k+pad)/2
              colnet_left: LC3
            space:
              width: 3k
              bind: [(3k+pad)/2, 0]
              colnet_left: LC4
    # Right-side keyboard.
    right:
      # Keys are added from right to left
      anchor:
        ref: left_meta_space
        shift: [14u, 0]
        rotate: 90
      # Rotate the keys so that switches are oriented
      # correctly.
      key:
        adjust:
          rotate: -90
      columns:
        meta:
          key:
            rownet_right: RR6
          rows:
            ctrl_r:
              width: 1.25k
              padding: (1.25k+pad + 1.25k+pad)/2
              shift: [0, (1.25k+pad-1u)/2]
              bind: [(1.25k+pad - 1u)/2, 0]
              colnet_right: RC8
            meta:
              width: 1.25k
              padding: (1.25k+pad + 1.25k+pad)/2
              bind: [(1.25k+pad), 0]
              colnet_right: RC7
            fn:
              width: 1.25k
              padding: (1.25k+pad + 1.25k+pad)/2
              bind: [(1.25k+pad), 0]
              colnet_right: RC6
            alt_r:
              width: 1.25k
              padding: (1.25k+pad + 3k+pad)/2
              bind: [(1.25k+pad), 0]
              colnet_right: RC5
            space_r:
              width: 3k
              bind: [(3k+pad)/2, 0]
              colnet_right: RC3
        bottom:
          key:
            rownet_right: RR5
          rows:
            shift_r:
              width: 2.75k
              padding: (2.75k+pad + 1u)/2
              shift: [0, (2.75k+pad - 1u)/2]
              bind: [(2.75k+pad - 1u)/2, 0]
              colnet_right: RC8
            slash:
              colnet_right: RC6
            period:
              colnet_right: RC5
            comma:
              colnet_right: RC4
            m:
              colnet_right: RC3
            n:
              colnet_right: RC2
            # Extra "B" on the right side
            b_r:
              colnet_right: RC1
        mid:
          key:
            rownet_right: RR4
          rows:
            enter:
              width: 2.25k
              padding: (2.25k+pad + 1u)/2
              shift: [0, (2.25k+pad - 1u)/2]
              bind: [(2.25k+pad - 1u)/2, 0]
              colnet_right: RC8
            quote:
              colnet_right: RC6
            colon:
              colnet_right: RC5
            l:
              colnet_right: RC4
            k:
              colnet_right: RC3
            j:
              colnet_right: RC2
            h:
              colnet_right: RC1
        top:
          key:
            rownet_right: RR3
          rows:
            pipe:
              width: 1.5k
              padding: (1.5k+pad + 1u)/2
              shift: [0, (1.5k+pad - 1u)/2]
              bind: [(1.5k+pad - 1u)/2, 0]
              colnet_right: RC8
            right_paren:
              colnet_right: RC7
            left_paren:
              colnet_right: RC6
            p:
              colnet_right: RC5
            o:
              colnet_right: RC4
            i:
              colnet_right: RC3
            u:
              colnet_right: RC2
            y:
              colnet_right: RC1
        num:
          key:
            rownet_right: RR2
          rows:
            backspace:
              width: 2k
              padding: (2k+pad + 1u)/2
              shift: [0, (2k+pad - 1u)/2]
              bind: [(2k+pad - 1u)/2, 0]
              colnet_right: RC8
            plus:
              colnet_right: RC7
            minus:
              colnet_right: RC6
            zero:
              colnet_right: RC5
            nine:
              colnet_right: RC4
            eight:
              colnet_right: RC3
            seven:
              colnet_right: RC2
            six_r:
              bind: [0, 0, 0, 1.1u-1]
              colnet_right: RC1
        function:
          key:
            spread: 1.5u
            bind: [0, 0, 1.5u, 0]
            rownet_right: RR1
          rows:
            f12:
              colnet_right: RC8
            f11:
              colnet_right: RC7
            f10:
              colnet_right: RC6
            f9:
              padding: 1.5u
              colnet_right: RC5
            f8:
              colnet_right: RC4
            f7:
              colnet_right: RC3
            f6:
              colnet_right: RC2
            # Extra F5 on the right side
            f5_r:
              bind: [0, 0, 0, 1.5u]
              colnet_right: RC1
        
outlines:
  left_outline:
    - what: rectangle
      where: /^left.*/
      bound: true
      size: [u, u]
      expand: 5
      fillet: 3
  right_outline:
    - what: rectangle
      where: /^right.*/
      bound: true
      size: [u, u]
      expand: 5
      fillet: 3
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [k, k]
  all:
    - name: left_outline
    - operation: add
      name: right_outline
    - operation: subtract
      name: keys

pcbs:
  jjongkbd:
    outlines:
      left:
        outline: left_outline
      right:
        outline: right_outline
      
    footprints:
      left_switch:
        what: mx
        where: /^left.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{colnet_left}}"
          to: "{{colrow}}"
      left_diode:
        what: diode
        where: /^left.*/
        params:
          from: "{{colrow}}"
          to: "{{rownet_left}}"
        adjust:
          shift: [0, -5]
      right_switch:
        what: mx
        where: /^right.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{colnet_right}}"
          to: "{{colrow}}"
      right_diode:
        what: diode
        where: /^right.*/
        params:
          from: "{{colrow}}"
          to: "{{rownet_right}}"
        adjust:
          shift: [0, -5]
      promicro_left:
        what: promicro
        params:
          orientation: "up"
          RAW: LRAW
          GND: LGND
          RST: LRST
          VCC: LVCC
          P21: LP21
          P20: LC7 
          P19: LC6
          P18: LC5
          P15: LC4
          P14: LC3
          P16: LC2
          P10: LC1
          P1: LP0 # no use
          P0: LP0 # no use
          P2: LR1
          P3: LR2
          P4: LR3
          P5: LR4
          P6: LR5
          P7: LR6
          P8: LP8 # no use
          P9: LP9 # no use
        where:
          ref: left_function_f5
          shift: [1.5u,-0.5u]
          rotate: -90
      promicro_right:
        what: promicro
        params:
          orientation: "up"
          RAW: RRAW
          GND: RGND
          RST: RRST
          VCC: RVCC
          P21: RP21
          P20: RP20 # no use
          P19: RC1
          P18: RC2
          P15: RC3
          P14: RC4
          P16: RC5
          P10: RC6
          P1: RP0 # no use
          P0: RP0 # no use
          P2: RR1
          P3: RR2
          P4: RR3
          P5: RR4
          P6: RR5
          P7: RR6
          P8: RP8 # no use
          P9: RP9 # no use
        where:
          ref: right_function_f5_r
          shift: [-1.5u,-0.5u]
          rotate: -90
      reset_left:
        what: button
        params:
          from: LGND
          to: LRST
        where: 
          ref: left_function_f5
          shift: [0.75u, 0]
      reset_right:
        what: button
        params:
          from: RGND
          to: RRST
        where:
          ref: right_function_f5_r
          shift: [-0.75u, 0]
      bat_left:
        what: jstph
        params:
          side: B
          pos: LRAW
          neg: LGND
        where: 
          ref: left_function_f5
          shift: [0.85u, 0.45u]
          rotate: -90
      bat_right:
        what: jstph
        params:
          side: B
          pos: RRAW
          neg: RGND
        where: 
          ref: right_function_f5_r
          shift: [-0.85u, 0.45u]
          rotate: 90

cases:
